const mongoose=require("mongoose")

const productSchema=new mongoose.Schema(
    {
        title:{
            type:String,
            required:true
        },
        desc:{
            type:String,
            required:true
        },
        mainImg:{
            type:String,
            required:true,
        },
        colorImg:{
            type:String,
            required:true,
        },
        size:{
            type:String,
        },
        color:{
            type:String,
        },
        types:{
            type:String,
        },
        price:{
            type:Number,
            required:true,
            min:0
        },
        categories:{
            type:Array,
            required:true
        },
        },{timestamps:true}
)
module.exports=mongoose.model("Product",productSchema);